site_name: HDH
nav:
  - Home: index.md
  - An introduction to DQC: intro.md
  - A brief introduction to HDHs: hdh.md
  - Quantum Computational Model mappings to HDHs: models.md
  - Visualizing HDHs: vis.md
  - The HDH Database: database.md
  - Partitioning HDHs for distribution: passes.md
  # - Contribution guide: contribution.md
  - Related publications and information: literature.md
theme: readthedocs

markdown_extensions:
  - attr_list
